import profile from "@assets/profile.png";

export const sampleStories = [
  { img: profile, username: "rami__ram_" },
  { img: profile, username: "sobin_cho_" },
  { img: profile, username: "junseo_511" },
  { img: profile, username: "y_jeongwon_" },
  { img: profile, username: "veggie_.hye" },
  { img: profile, username: "neck_soyeon" },
  { img: profile, username: "yellmin_g" },
  { img: profile, username: "lchyunee" },
  { img: profile, username: "rami__ram_" },
  { img: profile, username: "sobin_cho_" },
  { img: profile, username: "junseo_511" },
  { img: profile, username: "y_jeongwon_" },
  { img: profile, username: "veggie_.hye" },
  { img: profile, username: "neck_soyeon" },
  { img: profile, username: "yellmin_g" },
  { img: profile, username: "lchyunee" },
  { img: profile, username: "rami__ram_" },
  { img: profile, username: "sobin_cho_" },
  { img: profile, username: "junseo_511" },
  { img: profile, username: "y_jeongwon_" },
  { img: profile, username: "veggie_.hye" },
  { img: profile, username: "neck_soyeon" },
  { img: profile, username: "yellmin_g" },
  { img: profile, username: "lchyunee" },
  { img: profile, username: "rami__ram_" },
  { img: profile, username: "sobin_cho_" },
  { img: profile, username: "junseo_511" },
  { img: profile, username: "y_jeongwon_" },
  { img: profile, username: "veggie_.hye" },
  { img: profile, username: "neck_soyeon" },
  { img: profile, username: "yellmin_g" },
  { img: profile, username: "lchyunee" },
];
